name: global-mppi
channels:
  - nvidia/label/cuda-12.3.0
  - conda-forge
dependencies:
  - cuda
  - cudnn
  - python=3.12
  - pip
  - pytest
  - cvxpy
  - eigenpy
  - matplotlib
  - numpy
  - scipy
  - pip:
    - mosek
